id: PD2EF4366
initial_creation_type: input
source_metadata:
  title: Words of the Buddha
  language: pt
  description: 'A selection of works by the Buddha himself, many of which feature
    in the Kangyur (bka'' ''gyur), the Tibetan canonical collection of the Buddha''s
    Word:'
  volume:
    8165573d5bed41b2810e3e619558bd9e:
      title: The Auspicious Verses of the Seven Successive Buddhas
      parent: Auspiciousness
    595b1eadaea74b38ace5fdcc4597bcac:
      title: The Dhāraṇī of Amitāyus
      parent: Dhāraṇī
    a3ce2fad2fb44bf086309b1348501fae:
      title: The Dhāraṇī of Glorious Vajraṇakhī
      parent: Dhāraṇī
    de0d4ce8de7146768fa296b40943198a:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Dhāraṇī
    7c6ee42520b041969a6d436e6fdc9381:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Dhāraṇī
    472153fa29134a03bd74ea255de67112:
      title: The Noble Essence of Dependent Origination
      parent: Dhāraṇī
    3eccd6e703c64e8a9981c25bf2d6eef2:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Dhāraṇī
    e33133c157e44c118a8907edbc208707:
      title: The Noble Mārīcī Dhāraṇī
      parent: Dhāraṇī
    9756154ff6174ecfb9136a961cee879b:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Dhāraṇī
    77984b371e8249feb27e28743beaa5a1:
      title: Prayer for the Future of the Dharma
      parent: Prayers
    d7f89ac602ba4ecfb9feffbc7922a7f1:
      title: 'The Clarifying Light: A Prophecy of the Future'
      parent: Prophecy
    4b99189c43364d11b0024e4f90cb6820:
      title: The Song of the Vajra
      parent: Songs
    49850ddfa55a41a48e84d0a28bdb096f:
      title: Maitreya's Aspiration
      parent: Sūtra
    9e355c88e8f04123be89f0cb1e314725:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Sūtra
    cbc643ade25b435c9ff401f7d5ae5e75:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtra
    8de7bdcbf27b4cffb5437fa9c987fc41:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Sūtra
    421a92efdac74d0d8a5b9b2c9e789b09:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtra
    4e4479ae2ea14f9c8db018c00179e85b:
      title: The Noble Sūtra Teaching the Eleven Perceptions
      parent: Sūtra
    e5d209dc7435413ea5f8a92337a44975:
      title: The Noble Sūtra of Recalling the Three Jewels
      parent: Sūtra
    cf78cfe9ca314374a29715cb71ebd414:
      title: The Noble Sūtra of the Teaching on the Four Factors
      parent: Sūtra
    72b2924eed85493682c907e9091ae00f:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtra
    de87032b7a7c46c295259ec04a145e0b:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtra
    bbc69216fd714e73b19bf9e082e2577d:
      title: A Section of the Vajrakīla Root Tantra
      parent: Tantra
    a1657cf88b134b2e9486484f40e58fbd:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Tantra
    b41c6f9e6e864bb0b648edd771d1e025:
      title: The Lament of Rudra
      parent: Tantra
    5c2faf4ff4744ec8ac0748e7790eb161:
      title: The Praise to Tārā with Twenty-One Verses of Homage and The Excellent
        Benefits of Reciting the Praise
      parent: Tantra
    33b169f4bba04af2b13df8281b21489a:
      title: The Twenty-Eight Commitments
      parent: Tantra
    75ff1ca0c8174f58a19b143f42416b9e:
      title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
      parent: Tantra
    9c66a8302dd54192a9d37863b5ab799b:
      title: Verses of Confession 'Düsum Deshekma'
      parent: Tantra
created_at: '2022-03-01T02:07:32.765408'
last_modified_at: '2022-03-01T02:07:32.765411'
